# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install numpy -I
          pip install pytest torch
          pip install nose
          pip install -e .

      - name: Run pytest
        run: |
          for f in tests/test_torch.py tests/test_radix_major.py; do python "$f"; done
